// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using io.nem1.sdk.Infrastructure.Imported.FlatBuffers;

namespace io.nem1.sdk.Infrastructure.Buffers
{
    internal struct AggregateModificationRelativeChangeBuffer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  internal static AggregateModificationRelativeChangeBuffer GetRootAsAggregateModificationRelativeChangeBuffer(ByteBuffer _bb) { return GetRootAsAggregateModificationRelativeChangeBuffer(_bb, new AggregateModificationRelativeChangeBuffer()); }
  internal static AggregateModificationRelativeChangeBuffer GetRootAsAggregateModificationRelativeChangeBuffer(ByteBuffer _bb, AggregateModificationRelativeChangeBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  internal AggregateModificationRelativeChangeBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RelativeChange { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  internal static Offset<AggregateModificationRelativeChangeBuffer> CreateAggregateModificationRelativeChangeBuffer(FlatBufferBuilder builder,
      int RelativeChange = 0) {
    builder.StartObject(1);
    AggregateModificationRelativeChangeBuffer.AddRelativeChange(builder, RelativeChange);
    return AggregateModificationRelativeChangeBuffer.EndAggregateModificationRelativeChangeBuffer(builder);
  }

  internal static void StartAggregateModificationRelativeChangeBuffer(FlatBufferBuilder builder) { builder.StartObject(1); }
  internal static void AddRelativeChange(FlatBufferBuilder builder, int RelativeChange) { builder.AddInt(0, RelativeChange, 0); }
  internal static Offset<AggregateModificationRelativeChangeBuffer> EndAggregateModificationRelativeChangeBuffer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AggregateModificationRelativeChangeBuffer>(o);
  }
};


}
