// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using io.nem1.sdk.Infrastructure.Imported.FlatBuffers;

namespace io.nem1.sdk.Infrastructure.Buffers
{
    internal struct ImportanceTransferBuffer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  internal static ImportanceTransferBuffer GetRootAsImportanceTransferBuffer(ByteBuffer _bb) { return GetRootAsImportanceTransferBuffer(_bb, new ImportanceTransferBuffer()); }
  internal static ImportanceTransferBuffer GetRootAsImportanceTransferBuffer(ByteBuffer _bb, ImportanceTransferBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  internal ImportanceTransferBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  internal int TransactionType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal short Version { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal short Network { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal int Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int PublicKeyLen { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte PublicKey(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int PublicKeyLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetPublicKeyBytes() { return __p.__vector_as_arraysegment(14); }
  internal long Fee { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  internal int Deadline { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int Mode { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int RemotePublicKeyLen { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte RemotePublicKey(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int RemotePublicKeyLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetRemotePublicKeyBytes() { return __p.__vector_as_arraysegment(24); }

  internal static Offset<ImportanceTransferBuffer> CreateImportanceTransferBuffer(FlatBufferBuilder builder,
      int transactionType = 0,
      short version = 0,
      short network = 0,
      int timestamp = 0,
      int publicKeyLen = 0,
      VectorOffset publicKeyOffset = default(VectorOffset),
      ulong fee = 0,
      int deadline = 0,
      int mode = 0,
      int remotePublicKeyLen = 0,
      VectorOffset remotePublicKeyOffset = default(VectorOffset)) {
    builder.StartObject(11);
    ImportanceTransferBuffer.AddFee(builder, fee);
    ImportanceTransferBuffer.AddRemotePublicKey(builder, remotePublicKeyOffset);
    ImportanceTransferBuffer.AddRemotePublicKeyLen(builder, remotePublicKeyLen);
    ImportanceTransferBuffer.AddMode(builder, mode);
    ImportanceTransferBuffer.AddDeadline(builder, deadline);
    ImportanceTransferBuffer.AddPublicKey(builder, publicKeyOffset);
    ImportanceTransferBuffer.AddPublicKeyLen(builder, publicKeyLen);
    ImportanceTransferBuffer.AddTimestamp(builder, timestamp);
    ImportanceTransferBuffer.AddTransactionType(builder, transactionType);
    ImportanceTransferBuffer.AddNetwork(builder, network);
    ImportanceTransferBuffer.AddVersion(builder, version);
    return ImportanceTransferBuffer.EndImportanceTransferBuffer(builder);
  }

  internal static void StartImportanceTransferBuffer(FlatBufferBuilder builder) { builder.StartObject(11); }
  internal static void AddTransactionType(FlatBufferBuilder builder, int transactionType) { builder.AddInt(0, transactionType, 0); }
  internal static void AddVersion(FlatBufferBuilder builder, short version) { builder.AddShort(1, version, 0); }
  internal static void AddNetwork(FlatBufferBuilder builder, short network) { builder.AddShort(2, network, 0); }
  internal static void AddTimestamp(FlatBufferBuilder builder, int timestamp) { builder.AddInt(3, timestamp, 0); }
  internal static void AddPublicKeyLen(FlatBufferBuilder builder, int publicKeyLen) { builder.AddInt(4, publicKeyLen, 0); }
  internal static void AddPublicKey(FlatBufferBuilder builder, VectorOffset publicKeyOffset) { builder.AddOffset(5, publicKeyOffset.Value, 0); }
  internal static VectorOffset CreatePublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddFee(FlatBufferBuilder builder, ulong fee) { builder.AddUlong(6, fee, 0); }
  internal static void AddDeadline(FlatBufferBuilder builder, int deadline) { builder.AddInt(7, deadline, 0); }
  internal static void AddMode(FlatBufferBuilder builder, int mode) { builder.AddInt(8, mode, 0); }
  internal static void AddRemotePublicKeyLen(FlatBufferBuilder builder, int remotePublicKeyLen) { builder.AddInt(9, remotePublicKeyLen, 0); }
  internal static void AddRemotePublicKey(FlatBufferBuilder builder, VectorOffset remotePublicKeyOffset) { builder.AddOffset(10, remotePublicKeyOffset.Value, 0); }
  internal static VectorOffset CreateRemotePublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartRemotePublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static Offset<ImportanceTransferBuffer> EndImportanceTransferBuffer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ImportanceTransferBuffer>(o);
  }
  internal static void FinishImportanceTransferBufferBuffer(FlatBufferBuilder builder, Offset<ImportanceTransferBuffer> offset) { builder.Finish(offset.Value); }
};


}
