// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using io.nem1.sdk.Infrastructure.Imported.FlatBuffers;

namespace io.nem1.sdk.Infrastructure.Buffers
{
    internal struct ProvisionNamespaceTransactionBuffer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  internal static ProvisionNamespaceTransactionBuffer GetRootAsProvisionNamespaceTransaction(ByteBuffer _bb) { return GetRootAsProvisionNamespaceTransaction(_bb, new ProvisionNamespaceTransactionBuffer()); }
  internal static ProvisionNamespaceTransactionBuffer GetRootAsProvisionNamespaceTransaction(ByteBuffer _bb, ProvisionNamespaceTransactionBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  internal ProvisionNamespaceTransactionBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  internal int TransactionType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal short Version { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal short Network { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal int Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int PublicKeyLen { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte PublicKey(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int PublicKeyLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetPublicKeyBytes() { return __p.__vector_as_arraysegment(14); }
  internal ulong Fee { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  internal int Deadline { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int SinkAddressLength { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte SinkAddressString(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int SinkAddressStringLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetSinkAddressStringBytes() { return __p.__vector_as_arraysegment(22); }
  internal long RentalFee { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  internal int NewPartLength { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte NewPartString(int j) { int o = __p.__offset(28); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int NewPartStringLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetNewPartStringBytes() { return __p.__vector_as_arraysegment(28); }
  internal int ParentLength { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte ParentString(int j) { int o = __p.__offset(32); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int ParentStringLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetParentStringBytes() { return __p.__vector_as_arraysegment(32); }

  internal static Offset<ProvisionNamespaceTransactionBuffer> CreateProvisionNamespaceTransaction(FlatBufferBuilder builder,
      int transactionType = 0,
      short version = 0,
      short network = 0,
      int timestamp = 0,
      int publicKeyLen = 0,
      VectorOffset publicKeyOffset = default(VectorOffset),
      ulong fee = 0,
      int deadline = 0,
      int sinkAddressLength = 0,
      VectorOffset SinkAddressStringOffset = default(VectorOffset),
      long rentalFee = 0,
      int newPartLength = 0,
      VectorOffset newPartStringOffset = default(VectorOffset),
      uint parentLength = 0,
      VectorOffset parentStringOffset = default(VectorOffset)) {
    builder.StartObject(15);
    ProvisionNamespaceTransactionBuffer.AddRentalFee(builder, rentalFee);
    ProvisionNamespaceTransactionBuffer.AddFee(builder, fee);
    ProvisionNamespaceTransactionBuffer.AddParentString(builder, parentStringOffset);
    ProvisionNamespaceTransactionBuffer.AddParentLength(builder, parentLength);
    ProvisionNamespaceTransactionBuffer.AddNewPartString(builder, newPartStringOffset);
    ProvisionNamespaceTransactionBuffer.AddNewPartLength(builder, newPartLength);
    ProvisionNamespaceTransactionBuffer.AddSinkAddressString(builder, SinkAddressStringOffset);
    ProvisionNamespaceTransactionBuffer.AddSinkAddressLength(builder, sinkAddressLength);
    ProvisionNamespaceTransactionBuffer.AddDeadline(builder, deadline);
    ProvisionNamespaceTransactionBuffer.AddPublicKey(builder, publicKeyOffset);
    ProvisionNamespaceTransactionBuffer.AddPublicKeyLen(builder, publicKeyLen);
    ProvisionNamespaceTransactionBuffer.AddTimestamp(builder, timestamp);
    ProvisionNamespaceTransactionBuffer.AddTransactionType(builder, transactionType);
    ProvisionNamespaceTransactionBuffer.AddNetwork(builder, network);
    ProvisionNamespaceTransactionBuffer.AddVersion(builder, version);
    return ProvisionNamespaceTransactionBuffer.EndProvisionNamespaceTransaction(builder);
  }

  internal static void StartProvisionNamespaceTransaction(FlatBufferBuilder builder) { builder.StartObject(15); }
  internal static void AddTransactionType(FlatBufferBuilder builder, int transactionType) { builder.AddInt(0, transactionType, 0); }
  internal static void AddVersion(FlatBufferBuilder builder, short version) { builder.AddShort(1, version, 0); }
  internal static void AddNetwork(FlatBufferBuilder builder, short network) { builder.AddShort(2, network, 0); }
  internal static void AddTimestamp(FlatBufferBuilder builder, int timestamp) { builder.AddInt(3, timestamp, 0); }
  internal static void AddPublicKeyLen(FlatBufferBuilder builder, int publicKeyLen) { builder.AddInt(4, publicKeyLen, 0); }
  internal static void AddPublicKey(FlatBufferBuilder builder, VectorOffset publicKeyOffset) { builder.AddOffset(5, publicKeyOffset.Value, 0); }
  internal static VectorOffset CreatePublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddFee(FlatBufferBuilder builder, ulong fee) { builder.AddUlong(6, fee, 0); }
  internal static void AddDeadline(FlatBufferBuilder builder, int deadline) { builder.AddInt(7, deadline, 0); }
  internal static void AddSinkAddressLength(FlatBufferBuilder builder, int sinkAddressLength) { builder.AddInt(8, sinkAddressLength, 0); }
  internal static void AddSinkAddressString(FlatBufferBuilder builder, VectorOffset SinkAddressStringOffset) { builder.AddOffset(9, SinkAddressStringOffset.Value, 0); }
  internal static VectorOffset CreateSinkAddressStringVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartSinkAddressStringVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddRentalFee(FlatBufferBuilder builder, long rentalFee) { builder.AddLong(10, rentalFee, 0); }
  internal static void AddNewPartLength(FlatBufferBuilder builder, int newPartLength) { builder.AddInt(11, newPartLength, 0); }
  internal static void AddNewPartString(FlatBufferBuilder builder, VectorOffset newPartStringOffset) { builder.AddOffset(12, newPartStringOffset.Value, 0); }
  internal static VectorOffset CreateNewPartStringVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartNewPartStringVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddParentLength(FlatBufferBuilder builder, uint parentLength) { builder.AddUint(13, parentLength, 0); }
  internal static void AddParentString(FlatBufferBuilder builder, VectorOffset parentStringOffset) { builder.AddOffset(14, parentStringOffset.Value, 0); }
  internal static VectorOffset CreateParentStringVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartParentStringVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static Offset<ProvisionNamespaceTransactionBuffer> EndProvisionNamespaceTransaction(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ProvisionNamespaceTransactionBuffer>(o);
  }
  internal static void FinishProvisionNamespaceTransactionBuffer(FlatBufferBuilder builder, Offset<ProvisionNamespaceTransactionBuffer> offset) { builder.Finish(offset.Value); }
};


}
