// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using io.nem1.sdk.Infrastructure.Imported.FlatBuffers;

namespace io.nem1.sdk.Infrastructure.Buffers
{
    internal struct TransferTransactionBuffer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  internal static TransferTransactionBuffer GetRootAsTransferTransactionBuffer(ByteBuffer _bb) { return GetRootAsTransferTransactionBuffer(_bb, new TransferTransactionBuffer()); }
  internal static TransferTransactionBuffer GetRootAsTransferTransactionBuffer(ByteBuffer _bb, TransferTransactionBuffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  internal TransferTransactionBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  internal int TransactionType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal short Version { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal short Network { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  internal int Timestamp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int PublicKeyLen { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte PublicKey(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int PublicKeyLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetPublicKeyBytes() { return __p.__vector_as_arraysegment(14); }
  internal long Fee { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  internal int Deadline { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal int RecipientLen { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal sbyte Recipient(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  internal int RecipientLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal ArraySegment<byte>? GetRecipientBytes() { return __p.__vector_as_arraysegment(22); }
  internal long Amount { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  internal int MessageFieldLen { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal MessageBuffer? Message(int j) { int o = __p.__offset(28); return o != 0 ? (MessageBuffer?)(new MessageBuffer()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  internal int MessageLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
  internal int NoOfMosaics { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  internal MosaicBuffer? Mosaics(int j) { int o = __p.__offset(32); return o != 0 ? (MosaicBuffer?)(new MosaicBuffer()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  internal int MosaicsLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }

  internal static Offset<TransferTransactionBuffer> CreateTransferTransactionBuffer(FlatBufferBuilder builder,
      int transactionType = 0,
      short version = 0,
      short network = 0,
      int timestamp = 0,
      int publicKeyLen = 0,
      VectorOffset publicKeyOffset = default(VectorOffset),
      ulong fee = 0,
      int deadline = 0,
      int recipientLen = 0,
      VectorOffset recipientOffset = default(VectorOffset),
      long amount = 0,
      int messageFieldLen = 0,
      VectorOffset messageOffset = default(VectorOffset),
      int noOfMosaics = 0,
      VectorOffset mosaicsOffset = default(VectorOffset)) {
    builder.StartObject(15);
    TransferTransactionBuffer.AddAmount(builder, amount);
    TransferTransactionBuffer.AddFee(builder, fee);
    TransferTransactionBuffer.AddMosaics(builder, mosaicsOffset);
    TransferTransactionBuffer.AddNoOfMosaics(builder, noOfMosaics);
    TransferTransactionBuffer.AddMessage(builder, messageOffset);
    TransferTransactionBuffer.AddMessageFieldLen(builder, messageFieldLen);
    TransferTransactionBuffer.AddRecipient(builder, recipientOffset);
    TransferTransactionBuffer.AddRecipientLen(builder, recipientLen);
    TransferTransactionBuffer.AddDeadline(builder, deadline);
    TransferTransactionBuffer.AddPublicKey(builder, publicKeyOffset);
    TransferTransactionBuffer.AddPublicKeyLen(builder, publicKeyLen);
    TransferTransactionBuffer.AddTimestamp(builder, timestamp);
    TransferTransactionBuffer.AddTransactionType(builder, transactionType);
    TransferTransactionBuffer.AddNetwork(builder, network);
    TransferTransactionBuffer.AddVersion(builder, version);
    return TransferTransactionBuffer.EndTransferTransactionBuffer(builder);
  }

  internal static void StartTransferTransactionBuffer(FlatBufferBuilder builder) { builder.StartObject(15); }
  internal static void AddTransactionType(FlatBufferBuilder builder, int transactionType) { builder.AddInt(0, transactionType, 0); }
  internal static void AddVersion(FlatBufferBuilder builder, short version) { builder.AddShort(1, version, 0); }
  internal static void AddNetwork(FlatBufferBuilder builder, short network) { builder.AddShort(2, network, 0); }
  internal static void AddTimestamp(FlatBufferBuilder builder, int timestamp) { builder.AddInt(3, timestamp, 0); }
  internal static void AddPublicKeyLen(FlatBufferBuilder builder, int publicKeyLen) { builder.AddInt(4, publicKeyLen, 0); }
  internal static void AddPublicKey(FlatBufferBuilder builder, VectorOffset publicKeyOffset) { builder.AddOffset(5, publicKeyOffset.Value, 0); }
  internal static VectorOffset CreatePublicKeyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddFee(FlatBufferBuilder builder, ulong fee) { builder.AddUlong(6, fee, 9999999999999999999); }
  internal static void AddDeadline(FlatBufferBuilder builder, int deadline) { builder.AddInt(7, deadline, 0); }
  internal static void AddRecipientLen(FlatBufferBuilder builder, int recipientLen) { builder.AddInt(8, recipientLen, 0); }
  internal static void AddRecipient(FlatBufferBuilder builder, VectorOffset recipientOffset) { builder.AddOffset(9, recipientOffset.Value, 0); }
  internal static VectorOffset CreateRecipientVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  internal static void StartRecipientVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  internal static void AddAmount(FlatBufferBuilder builder, long amount) { builder.AddLong(10, amount, 0); }
  internal static void AddMessageFieldLen(FlatBufferBuilder builder, int messageFieldLen) { builder.AddInt(11, messageFieldLen, 0); }
  internal static void AddMessage(FlatBufferBuilder builder, VectorOffset messageOffset) { builder.AddOffset(12, messageOffset.Value, 0); }
  internal static VectorOffset CreateMessageVector(FlatBufferBuilder builder, Offset<MessageBuffer>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  internal static void StartMessageVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  internal static void AddNoOfMosaics(FlatBufferBuilder builder, int noOfMosaics) { builder.AddInt(13, noOfMosaics, 0); }
  internal static void AddMosaics(FlatBufferBuilder builder, VectorOffset mosaicsOffset) { builder.AddOffset(14, mosaicsOffset.Value, 0); }
  internal static VectorOffset CreateMosaicsVector(FlatBufferBuilder builder, Offset<MosaicBuffer>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  internal static void StartMosaicsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  internal static Offset<TransferTransactionBuffer> EndTransferTransactionBuffer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<TransferTransactionBuffer>(o);
  }
  internal static void FinishTransferTransactionBufferBuffer(FlatBufferBuilder builder, Offset<TransferTransactionBuffer> offset) { builder.Finish(offset.Value); }
};


}
