/* 
 * NIS1 API
 *
 * This document defines all the nis1 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kodtycoon@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


namespace io.nem1.sdk.Infrastructure.Imported.Client
{
    /// <exclude />
    public partial class GlobalConfiguration : Configuration
    {

    }
}